### ISSUE TITLE
reCaptcha not displayed 

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-faucet#25]
Sometimes the reCaptcha box is not shown during the inital page load.
Reloading the page is a temporary workaround but it does not solve the problem.

The reCaptcha box should be always visible, assuming that the page is loaded and the Lisk backend works properly.

**Comment by aniketk28** [comment]
Is there any fix available for this issue? captcha is not visible on the screen.

**Comment by lsilvs** [comment]
Hi @aniketk28,
it was fixed and deployed last week.

Make sure to clear the browser cache and try again, please.

Feel free to reopen this issue if still not working.
